### ISSUE TITLE
Handshake/extended API issue

### ISSUE THREAD

**Issue by astro** [feross/bittorrent-protocol#8] opened 2015-02-20 00:49 UTC
In `_onHandshake()` we emit the `'handshake'` event where we expect the handler to send with `handshake()` synchronously. If the handler defers handshaking the further body of `_onHandshake()` will send the `extended()` message before the actual protocol `handshake()`, which is a protocol violation.

Is this something you want to get sorted out? A deviation from the current assumptions about callers will probably break API compatibility.

**Comment by feross** [comment] 2015-02-20 02:32
Yep, confirmed. This issue hasn't affected webtorrent because we always call `handshake()` synchronously in the `'handshake'` event handler. PR welcome.

**Comment by feross** [comment] 2015-03-10 04:58
Released as 1.5.6.

**Closed by feross** 2015-03-10 04:58 UTC
